services:
  - type: web
    name: analysis-agent
    runtime: python
    buildCommand: |
      npm install
      npm run build:css
      pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.1
    plan: free
