services:
  - type: web
    name: analysis-agent
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: LLM_PROVIDER
        value: gemini
      - key: LLM_MODEL
        value: gemini-2.5-flash
      - key: LLM_TEMPERATURE
        value: 0.1
      - key: LLM_MAX_TOKENS
        value: 8192
      # LLM_API_KEY should be set securely in Render dashboard
